# Change these first
owner: gelokatil # Your GitHub organization or username, where this repository lives
repo: upptime-ceu # The name of this repository

sites:
  - name: www.ceu.es
    url: https://www.ceu.es
#  - name: www.uspceu.com
#    url: http://www.uspceu.es
#    maxResponseTime: 10000
#    expectedStatusCodes:
#      - 200
#      - 301
#      - 302
#    maxRedirects: 30
  - name: www.uchceu.es
    url: https://www.uchceu.es
    maxResponseTime: 10000
    expectedStatusCodes:
      - 200
      - 301
    __dangerous__insecure: true  
  - name: www.uaoceu.es  
    url: www.uaoceu.es
  - name: eduroam.ceu.es
    url: https://eduroam.ceu.es
  - name: www.ceuuniversities.com
    url: https://www.ceuuniversities.com
  - name: www.isepceu.es
    url: https://www.isepceu.es
  - name: www.escueladoctorado.ceu.es
    url: https://www.escueladoctorado.ceu.es
  - name: www.universidadmayoresceu.es
    url: https://www.universidadmayoresceu.es
  - name: www.escuelamagisterioceuvigo.es
    url: https://www.escuelamagisterioceuvigo.es
  - name: www.ciclosformativosceu.es
    url: https://www.ciclosformativosceu.es
  - name: institutofamilia.ceu.es
    url: https://institutofamilia.ceu.es
  - name: www.colegioceuvalencia.es
    url: https://www.colegioceuvalencia.es
  - name: www.colegioceumonteprincipe.es
    url: https://www.colegioceumonteprincipe.es
  - name: www.colegioceumurcia.es
    url: https://www.colegioceumurcia.es
  - name: www.colegioceualicante.es
    url: https://www.colegioceualicante.es
  - name: www.colegioceuvitoria.es
    url: https://www.colegioceuvitoria.es
  - name: www.colegioceusanchinarro.es
    url: https://www.colegioceusanchinarro.es
  - name: www.colegioceuclaudiocoello.es
    url: https://www.colegioceuclaudiocoello.es   
  - name: admision.uspceu.es
    url: https://admision.uspceu.es
  - name: www.caminoespiritualdelsur.com
    url: https://www.caminoespiritualdelsur.com
  - name: www.clubemprendedoresceu.com
    url: http://www.clubemprendedoresceu.com
  - name: www.angelayala.ceu.es
    url: https://www.angelayala.ceu.es
  - name: admisionint.uspceu.es
    url: https://admisionint.uspceu.es
  - name: revistas.uspceu.com
    url: https://revistas.uspceu.com
  - name: appsintranet.ceu.es
    url: https://appsintranet.ceu.es
  - name: admisionescolegios.ceu.es
    url: https://admisionescolegios.ceu.es
  - name: admision.isepceu.es
    url: https://admision.isepceu.es
  - name: admision.uaoceu.es
    url: https://admision.uaoceu.es
  - name: admisioniam.ceu.es
    url: https://admisioniam.ceu.es
  - name: exploria-erasmus.com
    url: http://exploria-erasmus.com
  - name: altasolicitudesinfo.ceu.es
    url: https://altasolicitudesinfo.ceu.es
  - name: gcet19.uspceu.es
    url: https://gcet19.uspceu.es
  - name: www.jornadas.ceu.es
    url: https://www.jornadas.ceu.es
  - name: www.culturajoven.es
    url: https://www.culturajoven.es
  - name: onceulab.com
    url: http://onceulab.com
  - name: centroaudiovisual.uspceu.com
    url: https://centroaudiovisual.uspceu.com
  - name: provuldig.com
    url: http://provuldig.com
  - name: www.idee.ceu.es
    url: https://www.idee.ceu.es
  - name: protocolo.isepceu.es
    url: https://protocolo.isepceu.es
  - name: www.educacionporderecho.com
    url: https://www.educacionporderecho.com
  - name: 100peliculashistoricas.ceu.es
    url: https://100peliculashistoricas.ceu.es
  - name: observatorio-btl.uchceu.es
    url: http://observatorio-btl.uchceu.es
  - name: www.ceumedia.es
    url: http://www.ceumedia.es
  - name: admisiontech.ceu.es
    url: https://admisiontech.ceu.es
  - name: www.vividores.org
    url: https://www.vividores.org
  - name: www.provuldig2.com
    url: https://www.provuldig2.com
  - name: www.acdp.es
    url: https://www.acdp.es
  - name: admisionuchinternacional.ceu.es
    url: https://admisionuchinternacional.ceu.es
  - name: www.ceualumni.com
    url: https://www.ceualumni.com
  - name: www.congreso.ceu.es
    url: https://www.congreso.ceu.es
  - name: yolibre.org
    url: https://yolibre.org
  - name: www.aguadelceu.com
    url: http://www.aguadelceu.com
  - name: comoenlos50.com
    url: https://comoenlos50.com
  - name: www.lanuevacarteradelaministra.com
    url: https://www.lanuevacarteradelaministra.com
  - name: www.ceuediciones.es
    url: https://www.ceuediciones.es
  - name: www.hubceu.es
    url: https://www.hubceu.es
  - name: www.graciasenunminuto.com
    url: https://www.graciasenunminuto.com
  - name: www.pormuchasrazones.es
    url: https://www.pormuchasrazones.es
  - name: www.noticiario1936.com
    url: http://www.noticiario1936.com
  - name: www.bibliotecaceu.es
    url: http://www.bibliotecaceu.es
  - name: haleoalicante.ceu.es
    url: https://haleoalicante.ceu.es
  - name: innovationweek.ceu.es
    url: https://innovationweek.ceu.es  
  - name: www.fundacionaho.es
    url: https://www.fundacionaho.es
  - name: francescoeconomy.ceu.es
    url: https://francescoeconomy.ceu.es
  - name: moodlecmtp.ceu.es
    url: https://moodlecmtp.ceu.es
  - name: iehistoricos.ceu.es
    url: https://iehistoricos.ceu.es  
  - name: institutodemocracia.ceu.es
    url: https://institutodemocracia.ceu.es
  - name: revistascientificas.uspceu.com
    url: https://revistascientificas.uspceu.com
  - name: cembio.uspceu.es
    url: https://cembio.uspceu.es
  - name: blog.ciclosformativosceu.es
    url: https://blog.ciclosformativosceu.es  
  - name: presslext.ceu.es
    url: https://presslext.ceu.es
  - name: citeceu.ceu.es
    url: https://citeceu.ceu.es
  - name: congreso.provuldig.com
    url: http://congreso.provuldig.com
  - name: www.educaceu.es
    url: http://www.educaceu.es  
  - name: manage.ceu.es
    url: https://manage.ceu.es
  - name: www.encuentrofamiliasceu.com
    url: https://www.encuentrofamiliasceu.com
  - name: rss.uchceu.es
    url: https://rss.uchceu.es
  - name: intranet.ceu.es
    url: https://intranet.ceu.es/loginceu/Login.aspx  
  - name: www.ceucyl.com
    url: https://www.ceucyl.com
  - name: blogs.uao.es
    url: https://blogs.uao.es
  - name: aulanews.uao.es
    url: https://aulanews.uao.es
  - name: tuestrellapolar.uaoceu.es
    url: https://tuestrellapolar.uaoceu.es  
  - name: enquestes.uao.es
    url: https://enquestes.uao.es
  - name: feriainternacional.ceu.es
    url: https://feriainternacional.ceu.es
  - name: 500pacifico.uaoceu.es
    url: https://500pacifico.uaoceu.es
  - name: www.ceudigital.com
    url: https://www.ceudigital.com  
  - name: admisionuch.ceu.es
    url: https://admisionuch.ceu.es
  - name: blog.uchceu.es
    url: https://blog.uchceu.es
  - name: medios.uchceu.es
    url: https://medios.uchceu.es
  - name: 3d.ceu.es
    url: https://3d.ceu.es 
  - name: www.goliads.com
    url: https://www.goliads.com
  - name: educationtalks.es
    url: https://educationtalks.es
  - name: www.ceule.es
    url: https://www.ceule.es
  - name: emplea.ceu.es
    url: https://emplea.ceu.es
  - name: neurofan.ceu.es
    url: https://neurofan.ceu.es
  - name: Chico RedIRIS
    check: "tcp-ping"
    url: 130.206.1.3
    port: 53
  - name: Sun RedIRIS
    check: "tcp-ping"
    url: 130.206.1.2
    port: 53
  - name: NS CEU
    check: "tcp-ping"
    url: 193.146.228.3
    port: 53    
  - name: VPN CEU
    check: "tcp-ping"
    url: vpn.ceu.es
    port: 10443
    
assignees:
  - gelokatil

workflowSchedule:
  graphs: "*/5 * * * *"
  responseTime: "*/5 * * * *"
  staticSite: "*/10 * * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"

user-agent: gelokatil

status-website:
  theme: light #light, dark, night or ocean.
  metaTags:
    - name: "robots"
      content: "noindex"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /upptime-ceu
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: CEU Uptime Status
#  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
#  introMessage: This is a status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /upptime-ceu
#    - title: GitHub
#      href: https://github.com/$OWNER/$REPO
  robotsText: "User-agent: * \n Disallow: /"
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
